name: ci

on:
  push:
    branches:
      - main

jobs:
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang
      - name: Build
        run: make -j$(nproc) CC=clang CXX=clang++
  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build
        run: make -j$(nproc) CC=gcc CXX=g++
