name: distribution

on:
  push:
    branches:
      - main

jobs:
  dist:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up environment
        run: |
          echo "tag=$(git describe --tags)" | tee -a $GITHUB_ENV
          echo "arch=${{ matrix.arch }}" | tee -a $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Distribution
        run: |
          ./dist.sh "$arch"
          mv chttpd-*.tar.gz "chttpd-$tag-$arch.tar.gz"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chttpd-${{ env.tag }}-${{ env.arch }}
          path: chttpd-${{ env.tag }}-${{ env.arch }}.tar.gz

