name: docker

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "version=$(echo "${{ github.ref_name }}" | sed 's/^v//')" >>$GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./dist.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zhongruoyu/chttpd:${{ env.version }},zhongruoyu/chttpd:latest
